//The only purpose of this document is to separate the data variable
//away from the main javascript file.

/*
    The following is a very long section containing all the unique latitudes and longitudes selected from the sqlite database using SELECT DISTINCT.
    
    I converted the csv file generated by this command to geojson using togeojson.com, and then beautified using
    http://archive.dojotoolkit.org/nightly/checkout/dojox/gfx/demos/beautify.html. I recommend using the second tool
    at your own risk. It's buggy and I had to manually edit the result for it to actually work. It was not a fun time. =P
*/

var data = {
	"type": "FeatureCollection",
	"features": [
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					126.9783,
					37.5985
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					100,
					15
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					115.275,
					39.8897
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					100.5014,
					13.754
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					119.3061,
					26.0614
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					116.3883,
					39.9289
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					121,
					23.5
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					120.1614,
					30.2936
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					122,
					13
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					118.0819,
					24.4798
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					118.7778,
					32.0617
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					72.8258,
					18.975
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					120.4586,
					41.5703
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					109.8222,
					40.6522
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					115.9333,
					28.55
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					104.0667,
					30.6667
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					103.8,
					1.3667
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					114.2734,
					30.5801
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					128.5911,
					35.8703
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-121.3244,
					37.9753
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					126.98,
					37.57
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					114.1667,
					22.25
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					119.6442,
					29.1068
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					117.1767,
					39.1422
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					121.525,
					25.0392
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					100.65,
					13.7667
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-122.2919,
					47.6606
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					9,
					51
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					10,
					56
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					15,
					62
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-97,
					38
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-0.13,
					51.5
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					133,
					-27
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-76.485,
					35.6169
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					120.35,
					22.6333
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-73.5833,
					45.5
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					5.75,
					52.5
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-102.3,
					21.8833
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					112.5,
					2.5
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-122.1206,
					47.6801
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-97.8526,
					40.5898
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-95,
					60
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-98.3987,
					29.4889
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-73.9981,
					40.7267
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-118.127,
					34.0953
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-121.4252,
					37.7396
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-98.23,
					26.2034
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-120.968,
					37.5566
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-122.2708,
					37.8044
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-118.2437,
					34.0522
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-94.1992,
					33.127
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-96.8353,
					32.9299
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-120.1955,
					47.494
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-74.4773,
					39.4899
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-111.9519,
					33.6748
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-122.1781,
					37.459
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-96.8067,
					32.7831
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-82.9378,
					40.0842
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-120.7464,
					37.8034
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					121.3997,
					31.0456
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-46.6658,
					-23.4733
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					24,
					56
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					2.35,
					48.86
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					13,
					55.6
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					142.488,
					-38.3818
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					113.25,
					23.1167
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-72,
					4
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-87.8945,
					43.0434
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-79.3801,
					43.6441
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					20,
					52
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					35,
					39
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-78.5,
					-0.2167
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-56.1708,
					-34.8581
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-70.6667,
					-33.45
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-100.3167,
					25.6667
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-103.3333,
					20.6667
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-99.13,
					19.43
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-55,
					-10
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					4,
					50.8333
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					44.493,
					56.7875
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					36.2527,
					49.9808
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-100.5667,
					19.6833
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-116.6167,
					31.8667
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-79.9,
					-2.1667
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-122.2536,
					37.8668
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					105.4803,
					35.1221
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-81.5513,
					35.9726
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-78.7279,
					42.9864
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-85.3718,
					39.9341
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-73.5804,
					45.5078
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					21.7344,
					38.2444
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-4,
					40
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					7.6333,
					51.9667
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-61.5167,
					10.65
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					39.2833,
					-6.8
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					35,
					-6
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-87.6368,
					41.8876
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-80.1273,
					26.1209
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-122.3826,
					37.7312
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-122.1312,
					37.4135
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-122.3321,
					47.6062
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					2.1741,
					41.3984
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					12.8333,
					42.8333
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-35.2167,
					-5.7833
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-69.3228,
					10.0739
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-99.1386,
					19.4342
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					120,
					-5
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					103.7922,
					36.0564
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					114.1333,
					22.5333
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					78.4744,
					17.3753
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					120.5954,
					31.3041
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-121.2519,
					38.937
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-77.4875,
					39.0437
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-122.8193,
					49.1641
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-81.7897,
					28.505
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-121.4944,
					38.5816
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-77.8735,
					35.9025
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-119.6452,
					36.5396
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-119.6753,
					39.3855
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-84.3972,
					33.9335
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-86.5,
					15
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-122.3255,
					37.563
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-111.8906,
					33.6119
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-122.348,
					47.6145
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-97.7565,
					30.4549
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-79.6377,
					40.6253
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-117.1324,
					32.8073
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-79.3952,
					43.6619
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-84.636,
					42.7257
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					101.6753,
					3.163
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					101.7,
					3.1667
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					101.6915,
					3.1013
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					101.672,
					3.1876
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					11.0683,
					49.4478
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					100,
					60
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-79.7398,
					37.8194
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-121.0169,
					37.6703
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-120.9501,
					37.6783
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					14.4667,
					50.0833
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					77.2,
					28.6
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					113.5325,
					34.6836
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					87.6005,
					43.801
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					106.2731,
					38.4681
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					105,
					35
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					123.4328,
					41.7922
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					126.65,
					45.75
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-95.9939,
					36.1554
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-77.0928,
					38.9376
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-80.2611,
					40.8768
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-120.8575,
					37.4744
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-120.8487,
					37.5372
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-121.946,
					37.425
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-121.8705,
					37.4404
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-80.2412,
					43.1242
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-66.5,
					18.25
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-122.4209,
					37.7957
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-8,
					53
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					30.2642,
					59.8944
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					18.05,
					59.3333
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					4.9167,
					52.35
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					13.3333,
					47.3333
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					8,
					47
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					6.1667,
					49.75
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-0.0931,
					51.5142
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-121.2908,
					37.9577
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-121.2546,
					37.4957
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-120.9736,
					37.6392
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-120.6367,
					37.3255
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-121.0376,
					37.7221
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-121.895,
					37.3394
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-87.6503,
					41.8745
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-121.1676,
					38.1165
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-120.9969,
					37.6391
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-121.2725,
					38.1302
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					151.2055,
					-33.8615
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-119.529,
					45.7788
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-77.2497,
					38.6582
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					116.9972,
					36.6683
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					117.2808,
					31.8639
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					2.3264,
					48.8331
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					34.75,
					31.5
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-120.8951,
					37.6767
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-122.0574,
					37.4192
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-120.7764,
					37.4249
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-86.1765,
					39.9738
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-80.2358,
					25.7267
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-74.8473,
					39.971
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-122.2687,
					37.555
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-76.7497,
					38.816
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-80.7018,
					41.1087
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-118.3852,
					34.0523
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-120.9502,
					37.7342
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-80.948,
					40.7212
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-122.0838,
					37.386
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-155.874,
					19.7108
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-121.2534,
					38.6501
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-121.1382,
					37.6527
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-121.0171,
					37.6369
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-121.4591,
					37.6201
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-121.1872,
					37.8311
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-117.7986,
					33.8138
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-78.5008,
					42.9038
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-76.2258,
					42.9732
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-118.309,
					34.1808
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-79.8697,
					43.257
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-121.7569,
					36.9102
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-121.0899,
					37.7187
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-121.2399,
					37.7399
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-77.0177,
					38.9085
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-120.8945,
					37.3934
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-81.0237,
					34.8889
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-82.5445,
					34.6417
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-74.2881,
					40.4832
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-121.8962,
					37.5155
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-122.882,
					45.446
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-122.3848,
					47.6847
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-96.2837,
					30.567
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-84.3915,
					33.7516
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-84.388,
					33.749
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-121.9886,
					37.5483
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-95.4945,
					29.9169
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-96.8028,
					32.7791
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-121.129,
					37.7576
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-92.1066,
					32.5206
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-115.1485,
					36.0877
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-115.1372,
					36.175
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					6.2333,
					52.4333
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					10.7389,
					59.9132
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-1.25,
					51.75
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					15.6833,
					47.6
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-18,
					65
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-8.6455,
					40.6443
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-8.626,
					40.8618
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					18.3933,
					47.5849
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					25,
					46
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					20,
					47
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-1.15,
					53.5333
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					32,
					49
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					2.3183,
					48.8763
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					29,
					47
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					53,
					32
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					55.3047,
					25.2582
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					25,
					43
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-87.65,
					41.85
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-119.7492,
					39.4896
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-82.6793,
					27.7709
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-94.1625,
					45.5608
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-122.0074,
					37.4249
				]
			},
			"properties": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					-117.6201,
					33.4228
				]
			},
			"properties": {}
		}
	]
}